services:
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # The vhost volume is only required if you
      # plan to obtain standalone certificates
      - vhost:/etc/nginx/vhost.d
      - conf:/etc/nginx/conf.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
    network_mode: bridge

  docker-gen:
    image: nginxproxy/docker-gen
    container_name: nginx-proxy-gen
    command: -notify-sighup nginx-proxy -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx-proxy
    volumes:
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.nginx-proxy.docker-gen"
    network_mode: bridge

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    environment:
      - DEFAULT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    network_mode: bridge

  draw:
    image: excalidraw/excalidraw:latest
    restart: unless-stopped
    healthcheck:
      disable: true
    network_mode: bridge
    environment:
      - VIRTUAL_HOST=${EXCALIDRAW_SUBDOMAIN}.${BASE_DOMAIN}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${EXCALIDRAW_SUBDOMAIN}.${BASE_DOMAIN}
      - LETSENCRYPT_MAIL=${LETSENCRYPT_EMAIL}
      - REACT_APP_BACKEND_V1_GET_URL=https://${EXCALIDRAW_SUBDOMAIN}.${BASE_DOMAIN}/api/v1/
      - REACT_APP_BACKEND_V2_GET_URL=https://${EXCALIDRAW_SUBDOMAIN}.${BASE_DOMAIN}/api/v2/
      - REACT_APP_BACKEND_V2_POST_URL=https://${EXCALIDRAW_SUBDOMAIN}.${BASE_DOMAIN}/api/v2/post

volumes:
  conf:
  vhost:
  html:
  certs:
  acme:
