services:
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # The vhost volume is only required if you
      # plan to obtain standalone certificates
      - vhost:/etc/nginx/vhost.d
      - conf:/etc/nginx/conf.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
    network_mode: bridge

  docker-gen:
    image: nginxproxy/docker-gen
    container_name: nginx-proxy-gen
    command: -notify-sighup nginx-proxy -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:rw
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    labels:
      - "com.github.nginx-proxy.docker-gen"
    network_mode: bridge

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    environment:
      - DEFAULT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    network_mode: bridge

  draw:
    image: excalidraw/excalidraw:latest
    restart: unless-stopped
    healthcheck:
      disable: true
    network_mode: bridge
    environment:
      - VIRTUAL_HOST=${EXCALIDRAW_SUBDOMAIN}.${BASE_DOMAIN}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${EXCALIDRAW_SUBDOMAIN}.${BASE_DOMAIN}
      - LETSENCRYPT_MAIL=${LETSENCRYPT_EMAIL}
      - REACT_APP_BACKEND_V1_GET_URL=https://${EXCALIDRAW_SUBDOMAIN}.${BASE_DOMAIN}/api/v1/
      - REACT_APP_BACKEND_V2_GET_URL=https://${EXCALIDRAW_SUBDOMAIN}.${BASE_DOMAIN}/api/v2/
      - REACT_APP_BACKEND_V2_POST_URL=https://${EXCALIDRAW_SUBDOMAIN}.${BASE_DOMAIN}/api/v2/post

  # mattermost
  mattermost:
    image: mattermost/mattermost-team-edition:latest
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - mattermost-config:/mattermost/config:rw
      - mattermost-data:/mattermost/data:rw
      - mattermost-logs:/mattermost/logs:rw
      - mattermost-plugins:/mattermost/plugins:rw
      - mattermost-client-plugins:/mattermost/client/plugins:rw
      - mattermost-bleve-indexes:/mattermost/bleve-indexes
      - /etc/localtime:/etc/localtime:ro

    environment:
      - SUBDOMAIN=${MATTERMOST_SUBDOMAIN}
      - LETSENCRYPT_HOST=${MATTERMOST_SUBDOMAIN}.${BASE_DOMAIN}
      - VIRTUAL_HOST=${MATTERMOST_SUBDOMAIN}.${BASE_DOMAIN}
      - VIRTUAL_PORT=8065
      - DOMAIN=${MATTERMOST_SUBDOMAIN}.${BASE_DOMAIN}
      - MM_BLEVESETTINGS_INDEXDIR=/mattermost/bleve-indexes
      - MM_SERVICESETTINGS_SITEURL=https://${MATTERMOST_SUBDOMAIN}.${BASE_DOMAIN}
      - MM_SERVICESETTINGS_FORWARD80TO443='false'
      - MATTERMOST_CONTAINER_READONLY='false'
      - MM_SQLSETTINGS_DRIVERNAME=postgres
      - MM_SQLSETTINGS_DATASOURCE=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_SERVER}:5432/${POSTGRES_DB}?sslmode=disable&connect_timeout=10

volumes:
  conf:
  vhost:
  html:
  certs:
  acme:
  mattermost-config:
  mattermost-data:
  mattermost-logs:
  mattermost-plugins:
  mattermost-client-plugins:
  mattermost-bleve-indexes:
